### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by kevinmarchese** [pauloamgomes/CockpitCMS-React-Static#9]
Hi, 
I'm sorry man but I can't get this to work either locally or on a droplet in digital ocean. I'd really love to try it but I'll gotten what the previous guy got "file not found issue" when I got past that I got the "Oh no! Something went terribly wrong:" webpage when calling /8088

"Call to a member function extend() on null"

/addons/cockpit_UniqueSlugs-master/bootstrap.php
 * @see       https://github.com/agentejo/cockpit/
 * 
 * @version   0.4.2
 * @author    Raffael Jesche
 * @license   MIT
 */

$this->module('uniqueslugs')->extend([

    'config' => function() {

        static $config;

If you could help me figure out the problem that be awesome. You know how awesome this is so its def worth packaging it in various ways ( if possible ). I don't mind docker but I'm not used to using it, so a little more extensive instructions would be worth it, not just for me, but for everyone. thank you for any insight here. kudos on this combo

**Comment by pauloamgomes** [comment]
Thanks @kevinmarchese , believe that was caused by an update on one of the addons that the install script uses, I updated the script to reflect to the correct path and that should solve your issue. Thanks.

In such case keep in mind that project is not updated for some time, so some of dependencies may be outdated (e.g. react static). I plan to do a further update when have some free time.

**Comment by kevinmarchese** [comment]
Thanks @pauloamgomes i'll look out for the update and give the update a try and get back to you. I'd settle for the original scripts which would have worked if thats even possible to get those? Do you maybe have a build I can grab? cause that would be awesome if you wouldn't mind uploading here https://www.dropbox.com/request/nLHqkmHUfIflH3LVXMHB
